### NumPy Array Creation

This section introduces different ways to create NumPy arrays, including from Python lists and using helper functions like `np.zeros`, `np.ones`, `np.arange`, and `np.linspace`.

In [1]:
import numpy as np

# Create from a standard Python list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)


# Create a 2D matrix from a list of lists
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

# Helper functions for rapid initialization
zeros_arr = np.zeros((2, 3))       # 2x3 matrix filled with 0s
ones_arr = np.ones((3, 3))         # 3x3 matrix filled with 1s
range_arr = np.arange(0, 10, 2)    # Numbers from 0 up to (but excluding) 10 stepping by 2
linear_space = np.linspace(0, 1, 5) # 5 evenly spaced numbers between 0 and 1

print("Range Array:", range_arr)
print("Linspace Array:", linear_space)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Range Array: [0 2 4 6 8]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]


### NumPy Array Indexing and Slicing

NumPy arrays support powerful indexing and slicing mechanisms, similar to Python lists but extended for multi-dimensional arrays. This allows for precise selection of elements or sub-arrays.

In [2]:
import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Individual element retrieval: [row, column]
print("Element at row 1, col 2:", matrix[1, 2]) # Returns 60

# Slicing: [row_start:row_end, col_start:col_end]
print("First two rows:\n", matrix[0:2, :])
print("Last column:", matrix[:, -1])

# Boolean indexing (Filtering)
print("Elements greater than 50:", matrix[matrix > 50])

Element at row 1, col 2: 60
First two rows:
 [[10 20 30]
 [40 50 60]]
Last column: [30 60 90]
Elements greater than 50: [60 70 80 90]


### NumPy Arithmetic and Mathematical Operations

NumPy arrays allow for efficient element-wise operations and provide a rich set of mathematical functions that can be applied to entire arrays or specific axes, leading to concise and fast computations.

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Scalar arithmetic
print("Scalar Multiplication (a * 2):", a * 2)

# Element-wise operations
print("Addition (a + b):", a + b)
print("Exponentiation (a ** 2):", a ** 2)

# Built-in math methods
matrix_data = np.array([[1, 2], [3, 4]])
print("Total Matrix Sum:", np.sum(matrix_data))
print("Column-wise Sum (Axis 0):", np.sum(matrix_data, axis=0))
print("Row-wise Sum (Axis 1):", np.sum(matrix_data, axis=1))


Scalar Multiplication (a * 2): [2 4 6]
Addition (a + b): [5 7 9]
Exponentiation (a ** 2): [1 4 9]
Total Matrix Sum: 10
Column-wise Sum (Axis 0): [4 6]
Row-wise Sum (Axis 1): [3 7]


### Real-world Application: BMI Calculation

This example demonstrates how NumPy's element-wise operations can be used for practical calculations, such as computing Body Mass Index (BMI). It also shows boolean indexing to filter data based on a condition.

In [4]:
import numpy as np

# Raw datasets (weights in kg, heights in meters)
weights = np.array([55, 82, 71, 95])
heights = np.array([1.65, 1.80, 1.72, 1.88])

# Formula: BMI = weight / (height^2)
bmi = weights / (heights ** 2)
print("Calculated BMIs:", np.round(bmi, 2))

# Identify who has a BMI over 25 (Overweight criteria)
overweight_mask = bmi > 25
print("Is overweight? (True/False):", overweight_mask)
print("Specific overweight BMIs:", np.round(bmi[overweight_mask], 2))

Calculated BMIs: [20.2  25.31 24.   26.88]
Is overweight? (True/False): [False  True False  True]
Specific overweight BMIs: [25.31 26.88]
